apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-0
  labels:
    type: local
    app: kafka-app
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kafka/0"


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-1
  labels:
    type: local
    app: kafka-app
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kafka/1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-2
  labels:
    type: local
    app: kafka-app
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kafka/2"
