apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka-app
spec:
  clusterIP: None
  selector:
    app: kafka-app
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
